USE Practice;

SELECT ADDR
,COUNT(MEM_NO) AS 회원수  
FROM CUSTOMER
WHERE GENDER ='MAN'
GROUP 
BY ADDR
HAVING COUNT(MEM_NO) < 100
ORDER
BY COUNT(MEM_NO) DESC;


SELECT ADDR
		,Count(MEM_NO) AS 회원수
  FROM   CUSTOMER
  WHERE GENDER = 'MAN'
  GROUP 
	  BY ADDR
	HAVING COUNT(MEM_NO) <100
    ORDER
    BY COUNT(MEM_NO) DESC;